### PR TITLE
adding the required files in order to start working on the project  

### PR DESCRIPTION
**Pull request by GorgiMitev**
*Adding the .github/workflows folder with the linters and tests files 
*Adding the rubocop file 
*Adding the readme file
*Adding the lib and bin folders with the .gitkeep file and our main.rb where we are gonna do the project

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 

### Hello @Solenka1

### To highlight:
-  Your bin, lib and linter setup looks good :+1: 

### To Improve:
- [ ] Add a description in the pull request
- [ ] In bin/main.rb `#!/usr/bin/env ruby` is the top line


_Please implement all the above mentioned requirements and ask for another code review whenver you are ready_

### **If you have any question related to the requirements please add a comment here and ping me on slack @GzimAsani**

HAPPY CODING :computer: :desktop_computer:

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 

### Hello @Solenka1, thank you for adding `#!/usr/bin/env ruby` in your code, but you forgot to implement the other requirement:
- [ ] Please add a description in your pull request

_Please implement all the above mentioned requirements and ask for another code review whenver you are ready_

### **If you have any question related to the requirements please add a comment here and ping me on slack @GzimAsani**

HAPPY CODING :computer: :desktop_computer:

**Comment by GorgiMitev** [comment]
Adding the files required for the project
*Adding the .github/workflows folder with the linters and tests files
*Adding the rubocop file
*Adding the readme file
*Adding the lib and bin folders with the .gitkeep file and our main.rb where we are gonna do the project

**Review by GzimAsani — APPROVED** [review]
# STATUS: ACCEPTED :green_circle: 

### Hi again @Solenka1, thank you for making the required changes :+1:, you may merge this millstone and good luck with the next one

**PS: Don't forget to submit a project completion form**

HAPPY CODING :computer:

**Review by umairarshadbutt — APPROVED** [review]
# Status: INVALID :red_circle: 

**Hi @Solenka1 **
I'm going to invalid this PR because it is approved already.
##

 **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
